## Encoders

- label encoder
- one hot encoder
- ordinal encoder

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## label encoder

In [7]:
from sklearn.preprocessing import LabelEncoder
color=['red','black','blue','green','orange']
le=LabelEncoder()
encode=le.fit_transform(color)
print(encode)

[4 0 1 2 3]

In [26]:
df = pd.read_csv("social_media.csv")

df.head()

,age,gender,job_type,daily_social_media_time,social_platform_preference,number_of_notifications,work_hours_per_day,perceived_productivity_score,actual_productivity_score,stress_level,sleep_hours,screen_time_before_sleep,breaks_during_work,uses_focus_apps,has_digital_wellbeing_enabled,coffee_consumption_per_day,days_feeling_burnout_per_month,weekly_offline_hours,job_satisfaction_score
0,56,Male,Unemployed,4.180940,Facebook,61,6.753558,8.040464,7.291555,4.0,5.116546,0.419102,8,False,False,4,11,21.927072,6.336688
1,46,Male,Health,3.249603,Twitter,59,9.169296,5.063368,5.165093,7.0,5.103897,0.671519,7,True,True,2,25,0.000000,3.412427
2,32,Male,Finance,NaN,Twitter,57,7.910952,3.861762,3.474053,4.0,8.583222,0.624378,0,True,False,3,17,10.322044,2.474944
3,60,Female,Unemployed,NaN,Facebook,59,6.355027,2.916331,1.774869,6.0,6.052984,1.204540,1,False,False,0,4,23.876616,1.733670
4,25,Male,IT,NaN,Telegram,66,6.214096,8.868753,NaN,7.0,5.405706,1.876254,1,False,True,1,30,10.653519,9.693060

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   age                             30000 non-null  int64
 1   gender                          30000 non-null  object
 2   job_type                        30000 non-null  object
 3   daily_social_media_time         27235 non-null  float64
 4   social_platform_preference      30000 non-null  object
 5   number_of_notifications         30000 non-null  int64
 6   work_hours_per_day              30000 non-null  float64
 7   perceived_productivity_score    28386 non-null  float64
 8   actual_productivity_score       27635 non-null  float64
 9   stress_level                    28096 non-null  float64
 10  sleep_hours                     27402 non-null  float64
 11  screen_time_before_sleep        27789 non-null  float64
 12  breaks_during_work              30000 non-null  int64
 13  uses_focus_apps                 30000 non-null  bool
 14  has_digital_wellbeing_enabled   30000 non-null  bool
 15  coffee_consumption_per_day      30000 non-null  int64
 16  days_feeling_burnout_per_month  30000 non-null  int64
 17  weekly_offline_hours            30000 non-null  float64
 18  job_satisfaction_score          27270 non-null  float64
dtypes: bool(2), float64(9), int64(5), object(3)
memory usage: 3.9+ MB

In [10]:
df.gender.unique()

array(['Male', 'Female', 'Other'], dtype=object)

In [11]:
enc=le.fit_transform(df['gender'])
enc

array([1, 1, 1, ..., 1, 0, 1], shape=(30000,))

## One Hot Encoder
- pandas

In [12]:
df=pd.DataFrame({"animals":["cat","Dog","fox"]})
print(df)

  animals
0     cat
1     Dog
2     fox

   animals_Dog  animals_cat  animals_fox
0            0            1            0
1            1            0            0
2            0            0            1

- sklearn

In [16]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(sparse_output=False)
dff=ohe.fit_transform(df)
print(dff)

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]

In [18]:
df.job_type.unique()

array(['Unemployed', 'Health', 'Finance', 'IT', 'Education', 'Student'],
      dtype=object)

In [19]:
en=pd.get_dummies(df["job_type"],prefix='job_type')
en

,job_type_Education,job_type_Finance,job_type_Health,job_type_IT,job_type_Student,job_type_Unemployed
0,False,False,False,False,False,True
1,False,False,True,False,False,False
2,False,True,False,False,False,False
3,False,False,False,False,False,True
4,False,False,False,True,False,False
...,...,...,...,...,...,...
29995,False,False,True,False,False,False
29996,False,False,True,False,False,False
29997,True,False,False,False,False,False
29998,True,False,False,False,False,False
29999,False,False,False,False,False,True

In [20]:
df=pd.concat([df,en],axis=1)
df

,age,gender,job_type,daily_social_media_time,social_platform_preference,number_of_notifications,work_hours_per_day,perceived_productivity_score,actual_productivity_score,stress_level,...,coffee_consumption_per_day,days_feeling_burnout_per_month,weekly_offline_hours,job_satisfaction_score,job_type_Education,job_type_Finance,job_type_Health,job_type_IT,job_type_Student,job_type_Unemployed
0,56,Male,Unemployed,4.180940,Facebook,61,6.753558,8.040464,7.291555,4.0,...,4,11,21.927072,6.336688,False,False,False,False,False,True
1,46,Male,Health,3.249603,Twitter,59,9.169296,5.063368,5.165093,7.0,...,2,25,0.000000,3.412427,False,False,True,False,False,False
2,32,Male,Finance,NaN,Twitter,57,7.910952,3.861762,3.474053,4.0,...,3,17,10.322044,2.474944,False,True,False,False,False,False
3,60,Female,Unemployed,NaN,Facebook,59,6.355027,2.916331,1.774869,6.0,...,0,4,23.876616,1.733670,False,False,False,False,False,True
4,25,Male,IT,NaN,Telegram,66,6.214096,8.868753,NaN,7.0,...,1,30,10.653519,9.693060,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,34,Female,Health,1.877297,Facebook,59,10.226358,3.348512,3.465815,8.0,...,4,5,21.776927,NaN,False,False,True,False,False,False
29996,39,Male,Health,4.437784,Instagram,46,4.692862,8.133213,6.659294,8.0,...,1,29,4.111370,6.155613,False,False,True,False,False,False
29997,42,Male,Education,17.724981,TikTok,64,10.915036,8.611005,8.658912,5.0,...,1,2,1.888315,6.285237,True,False,False,False,False,False
29998,20,Female,Education,3.796634,Instagram,56,6.937410,7.767076,6.895583,8.0,...,2,9,12.511871,7.854711,True,False,False,False,False,False
29999,44,Male,Unemployed,NaN,Twitter,70,8.069883,6.311227,5.402726,3.0,...,1,4,6.324954,7.388790,False,False,False,False,False,True

In [22]:
encode=ohe.fit_transform(df[['job_type']])
encode

array([[0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       ...,
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.]], shape=(30000, 6))

In [23]:
enc_df=pd.DataFrame(encode)

In [24]:
df=pd.concat([df,enc_df],axis=1)
df

,age,gender,job_type,daily_social_media_time,social_platform_preference,number_of_notifications,work_hours_per_day,perceived_productivity_score,actual_productivity_score,stress_level,...,coffee_consumption_per_day,days_feeling_burnout_per_month,weekly_offline_hours,job_satisfaction_score,0,1,2,3,4,5
0,56,Male,Unemployed,4.180940,Facebook,61,6.753558,8.040464,7.291555,4.0,...,4,11,21.927072,6.336688,0.0,0.0,0.0,0.0,0.0,1.0
1,46,Male,Health,3.249603,Twitter,59,9.169296,5.063368,5.165093,7.0,...,2,25,0.000000,3.412427,0.0,0.0,1.0,0.0,0.0,0.0
2,32,Male,Finance,NaN,Twitter,57,7.910952,3.861762,3.474053,4.0,...,3,17,10.322044,2.474944,0.0,1.0,0.0,0.0,0.0,0.0
3,60,Female,Unemployed,NaN,Facebook,59,6.355027,2.916331,1.774869,6.0,...,0,4,23.876616,1.733670,0.0,0.0,0.0,0.0,0.0,1.0
4,25,Male,IT,NaN,Telegram,66,6.214096,8.868753,NaN,7.0,...,1,30,10.653519,9.693060,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,34,Female,Health,1.877297,Facebook,59,10.226358,3.348512,3.465815,8.0,...,4,5,21.776927,NaN,0.0,0.0,1.0,0.0,0.0,0.0
29996,39,Male,Health,4.437784,Instagram,46,4.692862,8.133213,6.659294,8.0,...,1,29,4.111370,6.155613,0.0,0.0,1.0,0.0,0.0,0.0
29997,42,Male,Education,17.724981,TikTok,64,10.915036,8.611005,8.658912,5.0,...,1,2,1.888315,6.285237,1.0,0.0,0.0,0.0,0.0,0.0
29998,20,Female,Education,3.796634,Instagram,56,6.937410,7.767076,6.895583,8.0,...,2,9,12.511871,7.854711,1.0,0.0,0.0,0.0,0.0,0.0
29999,44,Male,Unemployed,NaN,Twitter,70,8.069883,6.311227,5.402726,3.0,...,1,4,6.324954,7.388790,0.0,0.0,0.0,0.0,0.0,1.0

## Ordinal encoder

In [25]:
from sklearn.preprocessing import OrdinalEncoder
education=[['ssc'],['ug'],['pg'],['inter']]
oe=OrdinalEncoder(categories=[['ssc','inter','ug','pg']])
ev=oe.fit_transform(education)
ev

array([[0.],
       [2.],
       [3.],
       [1.]])

In [28]:
df.social_platform_preference.unique()

array(['Facebook', 'Twitter', 'Telegram', 'TikTok', 'Instagram'],
      dtype=object)

In [33]:
df.social_platform_preference.unique()
oe=OrdinalEncoder(categories=[['Facebook', 'Twitter', 'Telegram', 'TikTok', 'Instagram']])
ev=oe.fit_transform(df[['social_platform_preference']])
ev

array([[0.],
       [1.],
       [1.],
       ...,
       [3.],
       [4.],
       [1.]], shape=(30000, 1))

In [36]:
enc_df=pd.DataFrame(ev)

In [37]:
df=pd.concat([df,enc_df],axis=1)
df

,age,gender,job_type,daily_social_media_time,social_platform_preference,number_of_notifications,work_hours_per_day,perceived_productivity_score,actual_productivity_score,stress_level,...,days_feeling_burnout_per_month,weekly_offline_hours,job_satisfaction_score,0,1,2,3,4,5,0
0,56,Male,Unemployed,4.180940,Facebook,61,6.753558,8.040464,7.291555,4.0,...,11,21.927072,6.336688,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,46,Male,Health,3.249603,Twitter,59,9.169296,5.063368,5.165093,7.0,...,25,0.000000,3.412427,0.0,0.0,1.0,0.0,0.0,0.0,1.0
2,32,Male,Finance,NaN,Twitter,57,7.910952,3.861762,3.474053,4.0,...,17,10.322044,2.474944,0.0,1.0,0.0,0.0,0.0,0.0,1.0
3,60,Female,Unemployed,NaN,Facebook,59,6.355027,2.916331,1.774869,6.0,...,4,23.876616,1.733670,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,25,Male,IT,NaN,Telegram,66,6.214096,8.868753,NaN,7.0,...,30,10.653519,9.693060,0.0,0.0,0.0,1.0,0.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,34,Female,Health,1.877297,Facebook,59,10.226358,3.348512,3.465815,8.0,...,5,21.776927,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0
29996,39,Male,Health,4.437784,Instagram,46,4.692862,8.133213,6.659294,8.0,...,29,4.111370,6.155613,0.0,0.0,1.0,0.0,0.0,0.0,4.0
29997,42,Male,Education,17.724981,TikTok,64,10.915036,8.611005,8.658912,5.0,...,2,1.888315,6.285237,1.0,0.0,0.0,0.0,0.0,0.0,3.0
29998,20,Female,Education,3.796634,Instagram,56,6.937410,7.767076,6.895583,8.0,...,9,12.511871,7.854711,1.0,0.0,0.0,0.0,0.0,0.0,4.0
29999,44,Male,Unemployed,NaN,Twitter,70,8.069883,6.311227,5.402726,3.0,...,4,6.324954,7.388790,0.0,0.0,0.0,0.0,0.0,1.0,1.0

## Column Trnsformer

In [60]:
df = pd.read_csv("social_media.csv")

In [61]:
num_col=df.select_dtypes(include="number").columns
print(num_col)

Index(['age', 'daily_social_media_time', 'number_of_notifications',
       'work_hours_per_day', 'perceived_productivity_score',
       'actual_productivity_score', 'stress_level', 'sleep_hours',
       'screen_time_before_sleep', 'breaks_during_work',
       'coffee_consumption_per_day', 'days_feeling_burnout_per_month',
       'weekly_offline_hours', 'job_satisfaction_score'],
      dtype='object')

In [62]:
cat_col=df.select_dtypes(include="object").columns
print(cat_col)

Index(['gender', 'job_type', 'social_platform_preference'], dtype='object')

In [63]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,StandardScaler

In [64]:
pre=ColumnTransformer(transformers=[('ohe',OneHotEncoder(),cat_col),('sc',StandardScaler(),num_col)])

In [65]:
pre

ColumnTransformer(transformers=[('ohe', OneHotEncoder(),
                                 Index(['gender', 'job_type', 'social_platform_preference'], dtype='object')),
                                ('sc', StandardScaler(),
                                 Index(['age', 'daily_social_media_time', 'number_of_notifications',
       'work_hours_per_day', 'perceived_productivity_score',
       'actual_productivity_score', 'stress_level', 'sleep_hours',
       'screen_time_before_sleep', 'breaks_during_work',
       'coffee_consumption_per_day', 'days_feeling_burnout_per_month',
       'weekly_offline_hours', 'job_satisfaction_score'],
      dtype='object'))])

In [66]:
prep=pre.fit_transform(df)
prep

array([[ 0.        ,  1.        ,  0.        , ..., -0.49250667,
         1.58872949,  0.64671729],
       [ 0.        ,  1.        ,  0.        , ...,  1.02054852,
        -1.42310937, -0.73190023],
       [ 0.        ,  1.        ,  0.        , ...,  0.15594556,
        -0.00530341, -1.17386876],
       ...,
       [ 0.        ,  1.        ,  0.        , ..., -1.46518501,
        -1.16373598,  0.62246125],
       [ 1.        ,  0.        ,  0.        , ..., -0.70865741,
         0.29548475,  1.36237611],
       [ 0.        ,  1.        ,  0.        , ..., -1.24903427,
        -0.55433216,  1.14272147]], shape=(30000, 28))

In [67]:
dfff=pd.DataFrame(prep)
dfff

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,1.250337,1.242338,-0.528229,-0.945166,-0.928250,0.947731,1.418913,-0.492507,1.588729,0.646717
1,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,-0.220971,0.113250,0.518419,-0.953806,-0.541903,0.632640,0.000496,1.020549,-1.423109,-0.731900
2,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.814815,-0.784643,-0.528229,1.422819,-0.614058,-1.572998,0.709705,0.155946,-0.005303,-1.173869
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,-1.282056,-1.686859,0.169536,-0.305512,0.273933,-1.257907,-1.417920,-1.249034,1.856513,-1.523336
4,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.659685,NaN,0.518419,-0.747649,1.302050,-1.257907,-0.708712,1.560925,0.040227,2.229050
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,-1.068468,-0.789017,0.867302,-0.696586,0.592471,1.262822,1.418913,-1.140959,1.568106,NaN
29996,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.296174,0.906626,0.867302,-2.359910,-1.341763,-0.627725,-0.708712,1.452850,-0.858384,0.561351
29997,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.532304,1.968364,-0.179346,-0.689032,0.304171,1.577914,-0.708712,-1.465185,-1.163736,0.622461
29998,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.115226,1.032089,0.867302,0.215728,-1.210827,-1.257907,0.000496,-0.708657,0.295485,1.362376
29999,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.395733,0.239426,-0.877112,0.181014,-0.049711,0.002458,-0.708712,-1.249034,-0.554332,1.142721