In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
# load dataset
df=pd.read_csv("loan_approved.csv")
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status (Approved)
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Loan_ID                 614 non-null    object
 1   Gender                  601 non-null    object
 2   Married                 611 non-null    object
 3   Dependents              599 non-null    object
 4   Education               614 non-null    object
 5   Self_Employed           582 non-null    object
 6   ApplicantIncome         614 non-null    int64
 7   CoapplicantIncome       614 non-null    float64
 8   LoanAmount              592 non-null    float64
 9   Loan_Amount_Term        600 non-null    float64
 10  Credit_History          564 non-null    float64
 11  Property_Area           614 non-null    object
 12  Loan_Status (Approved)  614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [4]:
df.tail()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status (Approved)
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [5]:
df.isnull().sum()

Loan_ID                    0
Gender                    13
Married                    3
Dependents                15
Education                  0
Self_Employed             32
ApplicantIncome            0
CoapplicantIncome          0
LoanAmount                22
Loan_Amount_Term          14
Credit_History            50
Property_Area              0
Loan_Status (Approved)     0
dtype: int64

In [6]:
num_cols = df.select_dtypes(include='number').columns
cat_cols = df.select_dtypes(include='object').columns

print("Numerical columns:", num_cols)
print("Categorical columns:", cat_cols)

Numerical columns: Index(['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History'],
      dtype='object')
Categorical columns: Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'Property_Area', 'Loan_Status (Approved)'],
      dtype='object')

In [7]:
for col in num_cols:
    df[col].fillna(df[col].mean(), inplace=True)

In [8]:
for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Loan_ID                 614 non-null    object
 1   Gender                  614 non-null    object
 2   Married                 614 non-null    object
 3   Dependents              614 non-null    object
 4   Education               614 non-null    object
 5   Self_Employed           614 non-null    object
 6   ApplicantIncome         614 non-null    int64
 7   CoapplicantIncome       614 non-null    float64
 8   LoanAmount              614 non-null    float64
 9   Loan_Amount_Term        614 non-null    float64
 10  Credit_History          614 non-null    float64
 11  Property_Area           614 non-null    object
 12  Loan_Status (Approved)  614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [10]:
y=df["Loan_Status (Approved)"]

In [11]:
## input varibles 13 columns
x=df.drop(["Loan_Status (Approved)"],axis=1)

In [12]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             614 non-null    object
 2   Married            614 non-null    object
 3   Dependents         614 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      614 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         614 non-null    float64
 9   Loan_Amount_Term   614 non-null    float64
 10  Credit_History     614 non-null    float64
 11  Property_Area      614 non-null    object
dtypes: float64(4), int64(1), object(7)
memory usage: 57.7+ KB

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder,StandardScaler
ct=ColumnTransformer(transformers=[("oe",OrdinalEncoder(),[0,1,2,3,4,5,11]),
                                   ("sc",StandardScaler(),[6,7,8,9,10])])

In [14]:
x_transformed=ct.fit_transform(x)

In [15]:
x_transformed

array([[ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  2.79850543e-01,  4.51640451e-01],
       [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00, ...,
        -2.19273315e-01,  2.79850543e-01,  4.51640451e-01],
       [ 2.00000000e+00,  1.00000000e+00,  1.00000000e+00, ...,
        -9.57640999e-01,  2.79850543e-01,  4.51640451e-01],
       ...,
       [ 6.11000000e+02,  1.00000000e+00,  1.00000000e+00, ...,
         1.26937121e+00,  2.79850543e-01,  4.51640451e-01],
       [ 6.12000000e+02,  1.00000000e+00,  1.00000000e+00, ...,
         4.83366900e-01,  2.79850543e-01,  4.51640451e-01],
       [ 6.13000000e+02,  0.00000000e+00,  0.00000000e+00, ...,
        -1.59727534e-01,  2.79850543e-01, -2.41044061e+00]],
      shape=(614, 12))

In [16]:
x_transformed=pd.DataFrame(x_transformed,columns=x.columns)
x_transformed

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,0.072991,-0.554487,0.000000,0.279851,0.451640
1,1.0,1.0,1.0,1.0,0.0,0.0,0.0,-0.134412,-0.038732,-0.219273,0.279851,0.451640
2,2.0,1.0,1.0,0.0,0.0,1.0,2.0,-0.393747,-0.554487,-0.957641,0.279851,0.451640
3,3.0,1.0,1.0,0.0,1.0,0.0,2.0,-0.462062,0.251980,-0.314547,0.279851,0.451640
4,4.0,1.0,0.0,0.0,0.0,0.0,2.0,0.097728,-0.554487,-0.064454,0.279851,0.451640
...,...,...,...,...,...,...,...,...,...,...,...,...
609,609.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.410130,-0.554487,-0.898095,0.279851,0.451640
610,610.0,1.0,1.0,3.0,0.0,0.0,0.0,-0.212557,-0.554487,-1.267279,-2.518655,0.451640
611,611.0,1.0,1.0,1.0,0.0,0.0,2.0,0.437174,-0.472404,1.269371,0.279851,0.451640
612,612.0,1.0,1.0,2.0,0.0,0.0,2.0,0.357064,-0.554487,0.483367,0.279851,0.451640
613,613.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.134412,-0.554487,-0.159728,0.279851,-2.410441

In [17]:
x.shape

(614, 12)

In [28]:
y.value_counts()

Loan_Status (Approved)
Y    422
N    192
Name: count, dtype: int64

In [19]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             614 non-null    object
 2   Married            614 non-null    object
 3   Dependents         614 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      614 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         614 non-null    float64
 9   Loan_Amount_Term   614 non-null    float64
 10  Credit_History     614 non-null    float64
 11  Property_Area      614 non-null    object
dtypes: float64(4), int64(1), object(7)
memory usage: 57.7+ KB

In [23]:
ct=ColumnTransformer(transformers=[("oe",OrdinalEncoder(),[0,1,2,3,4,5,11]),
                                   ( "sc",StandardScaler(),[6,7,8,9,10])])

In [24]:
x_train_transform=ct.fit_transform(x_train)
x_train_transform=pd.DataFrame(x_train_transform)
x_train_transform

,0,1,2,3,4,5,6,7,8,9,10,11
0,134.0,1.0,1.0,0.0,0.0,0.0,2.0,0.572692,-0.530923,-0.856351,-2.541668,0.445812
1,284.0,0.0,1.0,0.0,0.0,1.0,0.0,-0.007630,-0.530923,-0.504310,0.273912,-2.434503
2,449.0,1.0,0.0,0.0,0.0,0.0,2.0,-0.336575,-0.530923,-0.915024,0.273912,0.445812
3,465.0,1.0,1.0,1.0,0.0,0.0,0.0,-0.557137,-0.530923,-1.020636,0.273912,-0.008706
4,6.0,1.0,1.0,0.0,1.0,0.0,2.0,-0.488373,-0.052754,-0.621657,0.273912,0.445812
...,...,...,...,...,...,...,...,...,...,...,...,...
486,64.0,0.0,0.0,0.0,0.0,0.0,1.0,-0.258703,-0.530923,-0.433902,0.273912,0.445812
487,463.0,1.0,0.0,0.0,0.0,0.0,2.0,-0.563816,10.141764,-0.680331,0.273912,0.445812
488,267.0,1.0,1.0,0.0,0.0,0.0,2.0,8.771885,-0.530923,4.013543,-2.541668,0.445812
489,328.0,0.0,0.0,0.0,1.0,0.0,0.0,-0.506588,-0.530923,-0.961963,0.273912,0.445812
490,222.0,1.0,1.0,0.0,0.0,0.0,1.0,1.371147,-0.530923,3.379870,0.273912,0.445812

In [29]:
x_test_transform=ct.fit_transform(x_test)
x_test_transform=pd.DataFrame(x_test_transform)

In [30]:
from imblearn.over_sampling import SMOTE

In [31]:
smote=SMOTE()

In [34]:
x_train_smote,y_train_smote=smote.fit_resample(x_train_transform,y_train)

In [35]:
y_train_smote.value_counts()

Loan_Status (Approved)
Y    336
N    336
Name: count, dtype: int64

In [36]:
from sklearn.svm import SVC
model = SVC(kernel='linear')

In [37]:
model.fit(x_train_smote,y_train_smote)

SVC(kernel='linear')

In [38]:
y_pred = model.predict(x_test_transform)

In [40]:
# Accuracy
from sklearn.metrics import accuracy_score
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.8130081300813008

In [41]:
from sklearn.metrics import (accuracy_score,precision_score,recall_score,f1_score,confusion_matrix)

In [44]:
from sklearn.metrics import precision_score, recall_score, f1_score

print("Precision:", precision_score(y_test, y_pred, pos_label='Y'))
print("Recall:", recall_score(y_test, y_pred, pos_label='Y'))
print("F1-score:", f1_score(y_test, y_pred, pos_label='Y'))

Precision: 0.8058252427184466
Recall: 0.9651162790697675
F1-score: 0.8783068783068783

In [47]:
from sklearn.metrics import accuracy_score

# Training accuracy
train_pred = model.predict(x_train_smote)
train_accuracy = accuracy_score(y_train_smote, train_pred)

# Testing accuracy
test_pred = model.predict(x_test_transform)
test_accuracy = accuracy_score(y_test, test_pred)

print("Training Accuracy:", train_accuracy)
print("Testing Accuracy:", test_accuracy)

Training Accuracy: 0.7455357142857143
Testing Accuracy: 0.8130081300813008

In [61]:
## from sklearn.model_selection import GridSearchCV

# defining parameter range
param_grid = {
    'C': [0.1, 5, 10, 50, 60, 70],
    'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
    'random_state': (list(range(1, 20)))
}

model = SVC()

grid = GridSearchCV(model,param_grid,refit=True,verbose=1,scoring='f1',cv=5)

# fitting the model for grid search
grid.fit(x_train_smote,y_train_smote)

Fitting 5 folds for each of 570 candidates, totalling 2850 fits

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [0.1, 5, 10, 50, 60, 70],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'random_state': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                          13, 14, 15, 16, 17, 18, 19]},
             scoring='f1', verbose=1)

In [52]:
print(grid.best_params_)

{'C': 0.1, 'gamma': 1, 'random_state': 1}

In [55]:
clf=SVC(C=0.1,gamma=1,random_state=1)

In [56]:
clf.fit(x_train_smote, y_train_smote)

SVC(C=0.1, gamma=1, random_state=1)

In [58]:
y_train_pred = clf.predict(x_train_smote)
y_test_pred = clf.predict(x_test_transform)

In [59]:
from sklearn.metrics import accuracy_score

train_accuracy = accuracy_score(y_train_smote, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)

print("Train Accuracy:", train_accuracy)
print("Test Accuracy:", test_accuracy)

Train Accuracy: 0.7098214285714286
Test Accuracy: 0.6991869918699187

In [60]:

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [62]:
# Ensure SVC outputs probability for soft voting
clf1 = LogisticRegression(random_state=42)
clf2 = DecisionTreeClassifier(random_state=42)
clf3 = SVC(probability=True, random_state=42)

In [63]:
voting_clf = VotingClassifier(estimators=[ ('lr', clf1), ('dt', clf2), ('svc', clf3) ],voting='soft')

In [65]:
# Train
voting_clf.fit(x_train_smote, y_train_smote)

# Predict and evaluate
y_pred = voting_clf.predict(x_test_transform)

accuracy = accuracy_score(y_test, y_pred)

print(f"Voting Ensemble Accuracy: {accuracy:.4f}")

Voting Ensemble Accuracy: 0.6016

In [66]:
from sklearn.ensemble import StackingClassifier

In [67]:
# Base learners
base_learners = [
    ('dt', DecisionTreeClassifier()),
    ('svc', SVC(probability=True))
]

In [68]:
# Meta model
meta_model = LogisticRegression()

# Stacking classifier
stack = StackingClassifier(
    estimators=base_learners,
    final_estimator=meta_model,
    cv=5
)

# Train model
stack.fit(x_train_smote, y_train_smote)

StackingClassifier(cv=5,
                   estimators=[('dt', DecisionTreeClassifier()),
                               ('svc', SVC(probability=True))],
                   final_estimator=LogisticRegression())

In [69]:
# Predictions
y_pred = stack.predict(x_test_transform)

In [71]:
# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Stacking Classifier Accuracy:", accuracy)

Stacking Classifier Accuracy: 0.6016260162601627