In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [31]:
import pandas as pd

df = pd.read_csv("Medical_Classification_With_Text_Data.csv", encoding='latin1')
df.head()

,Unnamed: 0,0,a
0,0,Thyroid_Cancer,Thyroid surgery in children in a single insti...
1,1,Thyroid_Cancer,""" The adopted strategy was the same as that us..."
2,2,Thyroid_Cancer,coronary arterybypass grafting thrombosis ï¬b...
3,3,Thyroid_Cancer,Solitary plasmacytoma SP of the skull is an u...
4,4,Thyroid_Cancer,This study aimed to investigate serum matrix ...

In [3]:
df.shape

(7570, 3)

In [4]:
df.isnull().sum()

Unnamed: 0    0
0             0
a             0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7570 entries, 0 to 7569
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  7570 non-null   int64
 1   0           7570 non-null   object
 2   a           7570 non-null   object
dtypes: int64(1), object(2)
memory usage: 177.6+ KB

## TASK 2: Clean & Preprocess the Text

In [6]:
df["a"] = df["a"].str.lower()

#### Removing Punctions

In [7]:
import re
df["a"] = df["a"].apply(
    lambda x: re.sub(r'[^\w\s]', '', str(x))
)

#### Removing numbers

In [8]:
df["a"] = df["a"].apply(
    lambda x: re.sub(r'\d+', '', str(x))
)

#### Removing extra spaces

In [9]:
df["a"] = df["a"].apply(
    lambda x: re.sub(r'\s+', ' ', str(x)).strip()
)

In [10]:
df["a"]

0       thyroid surgery in children in a single instit...
1       the adopted strategy was the same as that used...
2       coronary arterybypass grafting thrombosis ïbri...
3       solitary plasmacytoma sp of the skull is an un...
4       this study aimed to investigate serum matrix m...
                              ...
7565    we report the case of a yearold man who presen...
7566    among synchronous colorectal cancers scrcs rep...
7567    the heterogeneity of cancer cells is generally...
7568    adipogenesis is the process through which mese...
7569    the periparturient period is one of the most c...
Name: a, Length: 7570, dtype: object

#### Remove stopwords

In [11]:
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\vinod\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\vinod\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [12]:
from nltk.corpus import stopwords
nltk.download('stopwords')
stop_words=set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\vinod\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [13]:
df["a"] = df["a"].apply(
    lambda x: ' '.join(
        word for word in str(x).split()
        if word.lower() not in stop_words
    )
)

#### Remove Lemmatize or stem the words

In [14]:
import nltk
from nltk.stem import WordNetLemmatizer

# Download once
nltk.download('wordnet')
nltk.download('omw-1.4')

lemmatizer = WordNetLemmatizer()

df["a"] = df["a"].apply(
    lambda x: ' '.join(
        lemmatizer.lemmatize(word) for word in str(x).split()
    )
)

df["a"].head()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\vinod\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\vinod\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

0    thyroid surgery child single institution osama...
1    adopted strategy used prior year based four ex...
2    coronary arterybypass grafting thrombosis ïbri...
3    solitary plasmacytoma sp skull uncommon clinic...
4    study aimed investigate serum matrix metallopr...
Name: a, dtype: object

In [15]:
def remove_emojis(text):
    emoji_pattern = re.compile(
        "["
        u"\U0001F600-\U0001F64F"  # emoticons
        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
        u"\U0001F680-\U0001F6FF"  # transport & map symbols
        u"\U0001F1E0-\U0001F1FF"  # flags
        "]+",
        flags=re.UNICODE
    )
    
    return emoji_pattern.sub(r'', str(text))

df["a"] = df["a"].apply(remove_emojis)

## TASK 3: Convert Text to Numerical Features

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(
    stop_words='english',
    max_features=5000
)

x = cv.fit_transform(df["a"])

In [17]:
bow_df = pd.DataFrame(
    x.toarray(),
    columns=cv.get_feature_names_out()
)

bow_df

,aa,aal,aand,ab,abbreviation,abc,abcam,abdomen,abdominal,aberrant,...,ïbroblasts,ïnal,ïnding,ïndings,ïow,ïrst,ïve,ïxed,ï½,ï½ms
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,2,0,0,0,...,0,0,0,0,2,3,0,2,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,2,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7565,0,0,0,0,0,0,0,0,0,0,...,0,3,0,2,0,2,0,0,0,0
7566,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
7567,0,0,0,0,0,1,0,0,0,0,...,1,0,0,4,13,0,0,0,0,0
7568,0,0,0,0,0,0,0,0,0,0,...,3,0,0,0,0,2,0,0,0,0
7569,33,64,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## TASK 4: Split the Data

In [18]:
df.drop(columns=["Unnamed: 0"], inplace=True)

In [19]:
X = df["a"]      # text data
y = df["0"]      # target labels

In [23]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

## TASK 5: Train Naïve Bayes Models

In [24]:
from sklearn.naive_bayes import MultinomialNB

In [25]:
model = MultinomialNB()
model.fit(x_train, y_train)

MultinomialNB()

In [26]:
y_pred = model.predict(x_test)

In [28]:
from sklearn.metrics import accuracy_score

print("Accuracy Score:")
print(accuracy_score(y_test, y_pred))

Accuracy Score:
0.8830911492734478

In [29]:
from sklearn.metrics import classification_report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Classification Report:
                precision    recall  f1-score   support

  Colon_Cancer       0.82      0.85      0.84       517
   Lung_Cancer       0.99      0.99      0.99       407
Thyroid_Cancer       0.87      0.84      0.85       590

      accuracy                           0.88      1514
     macro avg       0.89      0.89      0.89      1514
  weighted avg       0.88      0.88      0.88      1514

In [30]:
from sklearn.metrics import confusion_matrix


print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Confusion Matrix:
[[441   5  71]
 [  1 401   5]
 [ 95   0 495]]

In [32]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(x_train, y_train)

KNeighborsClassifier()

In [33]:
y_pred = knn.predict(x_test)

In [34]:
from sklearn.metrics import accuracy_score

print("Accuracy Score:")
print(accuracy_score(y_test, y_pred))

Accuracy Score:
1.0

In [35]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

[[517   0   0]
 [  0 407   0]
 [  0   0 590]]
                precision    recall  f1-score   support

  Colon_Cancer       1.00      1.00      1.00       517
   Lung_Cancer       1.00      1.00      1.00       407
Thyroid_Cancer       1.00      1.00      1.00       590

      accuracy                           1.00      1514
     macro avg       1.00      1.00      1.00      1514
  weighted avg       1.00      1.00      1.00      1514

In [36]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)

dt.fit(x_train, y_train)

DecisionTreeClassifier(random_state=42)

In [37]:
y_pred = dt.predict(x_test)

In [38]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 1.0

In [39]:
print(confusion_matrix(y_test, y_pred))

[[517   0   0]
 [  0 407   0]
 [  0   0 590]]

In [40]:
print(classification_report(y_test, y_pred))

                precision    recall  f1-score   support

  Colon_Cancer       1.00      1.00      1.00       517
   Lung_Cancer       1.00      1.00      1.00       407
Thyroid_Cancer       1.00      1.00      1.00       590

      accuracy                           1.00      1514
     macro avg       1.00      1.00      1.00      1514
  weighted avg       1.00      1.00      1.00      1514